### ISSUE TITLE
Open source the Q api and underlying software. 

### ISSUE THREAD

**Issue by shadedred** [daskeyboard/daskeyboard.io#1]
Is there any chance this software will ever be open source? Currently, there's a LOT of features the API is missing, batching signals, custom LED events, some way to trigger responses to events, all kinds of stuff. I'm sure you guys are working on it, but just as I'm writing open source clients to use the API, open source contributions to the underlying systems would be nice to see as well.

**Comment by supercobra** [comment]
Thank you for offering to help. However the software is not open source.
