### ISSUE TITLE
X50Q not detected

### ISSUE THREAD

**Issue by libmld-dev** [daskeyboard/daskeyboard.io#112]
I am running Das Keyboard Q 3.3.3 on my laptop, but my X50Q keyboard is not detected by the software. The window just says: "Plug your Q Device in." The keyboard itself works, but I can not make changes to the RGB profile or use any applets. I tried unplugging the keyboard and restarting my laptop without success.

System:
Memory: 16GB
Processor: Intel Core i7-4720HQ
GPU: NVIDIA GeForce GTX 970M
OS: Ubuntu 21.04 64-bit
Kernel Version: 5.11.0-37-generic
GNOME: 3.38.5
Windowing: X11

**Comment by suhrmann** [comment]
Mine got recognized after an initial Firmware update. (Initially) updating the X50Q requires a software only available for Windows:
https://www.daskeyboard.io/get-started/firmware/

![image](https://user-images.githubusercontent.com/6432295/141291620-8cbf61f5-06c7-4f6f-bd3c-b944074e23ee.png)

**Comment by libmld-dev** [comment]
I tried updating the firmware. The firmware updater showed, that my current firmware version is already the latest 0040. Nevertheless, I hit the Update button and the tool patched 0040 again. However, the keyboard is still not recognized on my ubuntu machine :(

EDIT: The keyboard is detected by a Windows 10 VM on the same machine through USB passthrough. This seems to be an issue with the Q Software on Linux!

**Comment by supercobra** [comment]
The X50Q Q software is only supported on Windows.
