### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by garettbynum** [daskeyboard/daskeyboard.io#115]
From URL: https://www.daskeyboard.io/get-started/software.md

“Das-Keyboard-Q_3.3.3.pkg” can’t be opened because Apple cannot check it for malicious software.

I was able to install the software originally, but not this update. Sudo doesn't help either.

**Comment by freddiehaddad** [comment]
Did you try to right-click on the file and click open?  You'll still see the warning, but you should be able to proceed after.  If you're double-clicking on the file from finder, you won't see the option to proceed with install.

**Comment by supercobra** [comment]
That solves the problem.
