### ISSUE TITLE
OpenSource the Das Keyboard Q software please.

### ISSUE THREAD

**Issue by freddiehaddad** [daskeyboard/daskeyboard.io#118]
Please open source the Das Keyboard Q software.  There is no reason for the code to be secret.  So many of these open issues would be fixed already if the code was open source.

Takes way too long waiting for a fix/response from Das.

**Comment by inxomnyaa** [comment]
This would be a very great step. It would also ensure new features

**Comment by supercobra** [comment]
No plan for this for now.

**Comment by inxomnyaa** [comment]
Very sad. This issue gave me some hope because i have been facing multiple issues with my keyboard so far. I will just send it back instead and get a different brand.

**Comment by freddiehaddad** [comment]
If there's no issue to open source the software, then here's a list of features that need immediate attention:

- Native M1 Mac support
- No reason for the Das Keyboard Q software to stay in the dock when the window is close
- Need a pub/sub model instead of every single app polling (think notifications, email, smtp, etc.)

**Comment by supercobra** [comment]
> No reason for the Das Keyboard Q software to stay in the dock when the window is close

I am not sure we can do this as Electron is managing that aspect. We'll check though.

> Need a pub/sub model instead of every single app polling (think notifications, email, smtp, etc.)

Most services, if not all (e.g. weather) do not support push. So poll is here to stay.
