### ISSUE TITLE
Issue from website page Getting Started with Q

### ISSUE THREAD

**Issue by lancealoha** [daskeyboard/daskeyboard.io#120]
From URL: https://www.daskeyboard.io/get-started/index.md

The connection for this site is not secure 

This notice appears everytime I click the link to download the software for my X50 daskeyboard

**Comment by BurnwaFuss** [comment]
Seconded. The specific link (as of today) is https://download.daskeyboard.com/q-software-releases/3.3.3/Das-Keyboard-Q_3.3.3.exe

Firefox reports Error code: SSL_ERROR_RX_RECORD_TOO_LONG. Chrome also fails. I've tried Windows and Mac.

Is there an alternate location to get the software?

**Comment by supercobra** [comment]
Use: [https://www.daskeyboard.io/get-started](https://www.daskeyboard.io/get-started/index.md)

Maybe it was a temp. glitch. All is working now.
