### ISSUE TITLE
Das Keyboard Q software for Mac not Notarized

### ISSUE THREAD

**Issue by robtete** [daskeyboard/daskeyboard.io#122]
Trying to install the software always results in message from MacOS: 

> Das-Keyboard-Q_3.3.3.pkg” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.

**Comment by supercobra** [comment]
This is a know issue. You can right click on the icon and select `open`. Then follow the instructions.

**Comment by robtete** [comment]
Unfortunately, on my work computer I do not have rights to do so. Are there plans to fix the application?

**Comment by supercobra** [comment]
Unfortunately there is one lib we use that is not signed by its author and we plan to replace it.

**Comment by supercobra** [comment]
After that we'll be able to get it signed.

**Comment by katiawheeler** [comment]
@supercobra Has this been solved? If not, what's the library and is it possible I could try and lend a hand? This is a real blocker to utilizing the macros on work computers - mine is also blocking this application due to Gatekeeper blocking it.
