### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by slj2222** [daskeyboard/daskeyboard.io#124]
From URL: https://www.daskeyboard.io/get-started/software.md

I just got a new keyboard, the 5Qs and tried to download the software, but my Mac says that is it malicious software. Any help would be great! Is there something I'm missing?

**Comment by supercobra** [comment]
macOS gives a warning because this software is not signed by Apple. You can safely ignore this warning.
