### ISSUE TITLE
The desktop app listens on all IP addresses

### ISSUE THREAD

**Issue by jordanbtucker** [daskeyboard/daskeyboard.io#13]
The desktop app listens on 0.0.0.0, which means it listens on all IP addresses. This is a security issue because anyone on the same network can read and write your signals without authenticating (unless you have a firewall properly configured). These signals may contain sensitive information.

An option should be provided to choose the listen IP address. One of those options should be 127.0.0.1 (localhost). When using 127.0.0.1, only apps running on your computer will have access to the local API. It is also recommended to make 127.0.0.1 the default setting.

I originally posted this on the [forum](https://qforum.daskeyboard.com/t/security-issue-desktop-app-listens-on-all-ip-addresses/745/1).

**Comment by MargauxMasson** [comment]
Implemented in release v2 beta 1.
