### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by jensenbox** [daskeyboard/daskeyboard.io#139]
I have a 5QS and would love to be able to do more with it with my own code but it would appear that there are no updates happening at all.

Did COVID kill your business? I suggest making money off the hardware and open-sourcing all your code. This would advance you way faster than what is happening now.

**Comment by Beanladen** [comment]
This is indeed not the correct place to post about issues in the software, but with the website ! Ran into the same trap 
because former posts had been answered despite of this. 
You have to post software issues via https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form-selection

**Comment by Mubramaj** [comment]
We made a new version recently and are accepting applet contributions https://www.daskeyboard.io/applet-development/
