### ISSUE TITLE
List of all signal areas

### ISSUE THREAD

**Issue by MikeFoden** [daskeyboard/daskeyboard.io#14]
Can you please add a list of all signal areas available?

**Comment by MargauxMasson** [comment]
You can find all the zone mapping correspondences in this folder: [](https://github.com/DasKeyboard/q/tree/master/zone_mapping)

**Comment by MargauxMasson** [comment]
You can get the zones at this address: https://q.daskeyboard.com/api/1.0/device_definitions

**Comment by MikeFoden** [comment]
Why did you delete your previous comment with the txt?
