### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by shagie** [daskeyboard/daskeyboard.io#141]
From URL: https://www.daskeyboard.io/get-started/software.md

The Mac download appears to be silicon only.  If this is the case, please indicate it on the download page with information about support for Intel Macs.
<img width="870" alt="Screenshot 2024-03-24 at 5 29 38 PM" src="https://github.com/daskeyboard/daskeyboard.io/assets/2193323/b8ca26ed-c7b4-495c-b12e-c4aa92a6bce3">

**Comment by Mubramaj** [comment]
We have a specific build for intel now
