### ISSUE TITLE
Das keyboard 5q update firmware fails

### ISSUE THREAD

**Issue by marcosikkens** [daskeyboard/daskeyboard.io#146]
I've got one of the kickstarter 5q keyboards. I updated it once and is working fine.

However when I tried to upgrade the firmware to the latest version it just says upgrade failed and nothing happens.

This is on a fresh windows 11 install, I also tried running the software as administrator but that didn't didn't help.

**Comment by Mubramaj** [comment]
Hi @marcosikkens ,

Can you please open a ticket at https://daskeyboard.mojohelpdesk.com/mc/up/new-ticket/19780 with your current firmware version and I will help you troubleshoot from there.

Thanks
