### ISSUE TITLE
Q Software 4.1.5 - Das Keyboard 4Q - Q key makes keyboard non-responsive until unplugged and replugged

### ISSUE THREAD

**Issue by sporkwitch** [daskeyboard/daskeyboard.io#149]
From URL: https://www.daskeyboard.io/get-started/software.md

Windows 10 Pro
Ryzen 9 3950x
4x32GB DDR4 3600
RTX3080
Das Keyboard 4Q

Pressing the Q button when set to mute volume causes the keyboard to cease responding until unplugging and plugging it back in.  Closing the Q software (right click and exit in system tray) does not change this behaviour, nor does setting it to Notification instead of mute.  Keyboard is running the firmware update I was prompted to install when reinstalling everything today.  This is a clean Windows 10 Pro install.

Significant impact to usability.  Previously, due to stability issues with the software, I'd use the Q software to set RGB then close it, and use AutoHotKey to remap the Q button to mute, which worked excellent.  Since these updates, the button instantly kills the keyboard.

Unrelated, but I also notice there's no way to prevent Q from starting with the OS in the current version.

These issues already have me investigating potential alternatives to my Das Keyboard.

**Comment by Mubramaj** [comment]
It looks like a firmware issue. Could you open a ticket at https://daskeyboard.mojohelpdesk.com/
