### ISSUE TITLE
Das Keyboard 5 Q Software Crashes on Launch

### ISSUE THREAD

**Issue by ryderdonahue** [daskeyboard/daskeyboard.io#16]
Every time I launch the software it immediately crashes. 
I have tried reinstalling and I cannot find any logs in the install directories.

**Comment by MargauxMasson** [comment]
Did you look in the folder .quio ?

**Comment by ryderdonahue** [comment]
@MargauxMasson I dont see any in the folder: `AppData\Local\Programs\das-keyboard-q`
![image](https://user-images.githubusercontent.com/1029224/37377866-af240154-26e9-11e8-8be3-faf4460fdfac.png)
none of these look like logs to me

**Comment by MargauxMasson** [comment]
The log is in the hidden folder .quio under the name quio.log

**Comment by fabiendv** [comment]
Our latest releases address these issues.
[Changelog](https://www.daskeyboard.io/updates/changelog/)
[Download](https://www.daskeyboard.io/get-started/software/)
