### ISSUE TITLE
Issue from website page Get Started: Download

### ISSUE THREAD

**Issue by NimoyLove** [daskeyboard/daskeyboard.io#18]
From URL: https://daskeyboard.github.io/get-started/download.md

When trying to download I get this error: 

"NoSuchKeyThe specified key does not exist.Das-Keyboard-Q-Setup-1.0.0-beta.43.exe2EEC2E15664058DEh87pyuxjIni6ev08pnlR655ojGoI2LBHdNJnAx2wGT5civMyWxiMfAempqgQiGnxf1YDR+RLYJM="

**Comment by lnr0626** [comment]
Me as well.

**Comment by lnr0626** [comment]
https://s3-us-west-2.amazonaws.com/q-software-releases/Das%20Keyboard%20Q%20Setup%201.0.0-beta.45.exe seemed to work for me

**Comment by NimoyLove** [comment]
Thanks!
