### ISSUE TITLE
Issue from website page Get Started: Download

### ISSUE THREAD

**Issue by Casey-Bateman** [daskeyboard/daskeyboard.io#20]
From URL: https://daskeyboard.github.io/get-started/download.md

![image](https://user-images.githubusercontent.com/4195196/40427350-10c1aae6-5e63-11e8-8ee1-20c1901248c3.png)

Everytime I go to click to download the Q desktop, i get this message. I think one of your S3 Pointers is off.

**Comment by hlfshell** [comment]
Not on the Das team, but some research pointed me towards this link:
https://s3-us-west-2.amazonaws.com/q-software-releases/Das%20Keyboard%20Q%20Setup%201.0.0-beta.45.exe

**Comment by camilleblrt** [comment]
The new software version is online on this link: [https://daskeyboard.github.io/get-started/download/]( https://daskeyboard.github.io/get-started/download/).
