### ISSUE TITLE
Q API: Update Colors

### ISSUE THREAD

**Issue by james-ingold** [daskeyboard/daskeyboard.io#23]
Can the Q API include a way to update keyboard colors? I'm on a mac and I can't update the keyboard colors with the desktop app, I've got the default rainbow color scheme going. It would be nice to be able to do that over the API. 

Thanks,

James

**Comment by Mubramaj** [comment]
I am sorry you can't update the color with the API on MAC but this is coming soon. 
However there is a set of built in profiles, here is a tutorial on how to access them. (you will have to update the firmware to the latest version)
https://daskeyboard.mojohelpdesk.com/help/article/199506

You can find the latest firmware version here: https://www.daskeyboard.io/get-started/download/

**Comment by fermion** [comment]
Hey @AhmedLoud, when will be able to do everything (update firmware, etc.) from a Mac?

**Comment by Mubramaj** [comment]
Hi @fermion ,
We have a beta version, for MAC, you still have to do the firmware upgrade from a Windows machine though.
If you want to receive the beta versions you will have to sign up for it here
https://docs.google.com/forms/d/e/1FAIpQLSdpQgxCFNOxWbiUu8PImeNb_je11C9-GguJRFGwK_Uf0YFmBw/viewform?usp=sf_link

**Comment by fermion** [comment]
@AhmedLoud 👋 thanks for the quick reply!

> you still have to do the firmware upgrade from a Windows machine though

I'm asking when that ☝️ won't be a requirement for being able to do a firmware upgrade. As it is right now I've unboxed my keyboard, plugged it into my machine and I see this:

<img width="472" alt="screen shot 2018-09-12 at 16 42 48" src="https://user-images.githubusercontent.com/2804/45452052-ea83c580-b6aa-11e8-86e2-3b9d56f3ea11.png">

As a Mac user with no access to a Windows machine it's a little disappointing to get this keyboard and not have the basics covered on my platform. I would have expected to see big red warnings before purchasing that Mac support wasn't yet at parity.

**Comment by fermion** [comment]
@AhmedLoud do you know if I'd be able to do this using Windows running inside of VirtualBox on my Mac? I'm about to try it regardless but I figured I'd look for a short circuit if it's known to not work.

**Comment by fermion** [comment]
For posterity's sake this didn't work using Virtualbox.

**Comment by fabiendv** [comment]
We now have implemented the firmware upgrade utility inside the Das Keyboard Q Software.
