### ISSUE TITLE
Issue from website page Get Started: Download

### ISSUE THREAD

**Issue by asmalls911** [daskeyboard/daskeyboard.io#24]
From URL: https://www.daskeyboard.io/get-started/download.md

Zipped file for firmware complains that it cannot be opened on my mac because it is a windows file, despite the website suggesting that the firmware update is for All OS.

**Comment by Mubramaj** [comment]
Hi,
There is a firmware for MAC keyboards but you have to upgrade your keyboard from a windows machine.

**Comment by fabiendv** [comment]
Our latest releases address these issues.
[Changelog](https://www.daskeyboard.io/updates/changelog/)
[Download](https://www.daskeyboard.io/get-started/software/)
