### ISSUE TITLE
Issue opening Q Desktop after 2.0.0-7 update

### ISSUE THREAD

**Issue by rx13** [daskeyboard/daskeyboard.io#26]
Windows 10 x64
beta 2.0.0-7 software 
DasKeyboard 5Q

The Q desktop app never loads, just a blank screen. Keyboard colors are no longer working on the keyboard (probably because the service/app are hung).

Upon rebooting the computer, colors will work during shutdown, but when computer comes back online they go dark again. seems like maybe something in the app is hung and doesn't fix until it is killed on shutdown

**Comment by Mubramaj** [comment]
Hi
Did you try to delete the .quio folder located in your home folder.
C:\Users\{{YouUserName}}\.quio and restart the app

**Comment by rx13** [comment]
That does appear to solve it -- it may be beneficial to include the option to "fresh" install in new versions (which would clean up that folder, etc)
