### ISSUE TITLE
Issue from website page Das Keyboard Q OAuth authentication API

### ISSUE THREAD

**Issue by jfrmilner** [daskeyboard/daskeyboard.io#29]
From URL: https://www.daskeyboard.io/q-authentication.md

Refreshing the Oauth token
curl -X POST -H "Content-Type: application/json" -d '{"client_id": "CLIENT_ID", "grant_type": "refresh_token", "**refreshToken**": "REFRESH_TOKEN"}' https://q.daskeyboard.com/oauth/1.4/token

Should be
curl -X POST -H "Content-Type: application/json" -d '{"client_id": "CLIENT_ID", "grant_type": "refresh_token", "refresh_token": "REFRESH_TOKEN"}' https://q.daskeyboard.com/oauth/1.4/token

**Comment by Mubramaj** [comment]
Good catch, thank you
