### ISSUE TITLE
Firmware Update Failed

### ISSUE THREAD

**Issue by zach-wildfig** [daskeyboard/daskeyboard.io#36]
I've attempted to update my firmware to the newest several times. However, each time the keyboard flickers and cycles RGB patterns before ultimately telling me the firmware upgrade has failed.

**Comment by Mubramaj** [comment]
Hi Zach, can you try to stop the service before running the FW upgrade. 
You will have to look for `services` in the windows navbar search and look for 'Das Keyboard Q Service`
Right click on it then click stop. When the FW upgrade is done start it again.


Also if you have other bugs to report can you please use [forum](https://qforum.daskeyboard.com)

Thank you 
![image](https://user-images.githubusercontent.com/20217427/43791369-17908414-9a3b-11e8-93d6-17a4e92ffc81.png)

**Comment by Mubramaj** [comment]
We now have implemented the firmware upgrade utility inside the Das Keyboard Q Software.
