### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by macdja38** [daskeyboard/daskeyboard.io#4]
These instructions seem to be for linux?

https://github.com/DasKeyboard/q/blob/master/q-api-doc.md#step-by-step-das-keyboard-q-rest-api-documentation

The... software as far as I know only runs on Windows, so it would be nice to have windows instructions to find the port.

Also how is the port generated, it seemed to stay the same at 27301 even after a re-install?

**Comment by supercobra** [comment]
Port is always 27301. Documentation updated.
