### ISSUE TITLE
Issue from website page Display CPU activity on your device

### ISSUE THREAD

**Issue by Daeden-JL** [daskeyboard/daskeyboard.io#44]
From URL: https://www.daskeyboard.io/script-examples/cpu-percentage.md

The shell script seems to be missing. The page just displays the node script with extra whitespace.

**Comment by supercobra** [comment]
It's better to access it from the web site: https://www.daskeyboard.io/script-examples/cpu-percentage/

And on Github: https://github.com/DasKeyboard/Daskeyboard.io/blob/master/_includes/script-examples/cpu-percentage/shell.md

**Comment by supercobra** [comment]
Node script on Github: https://github.com/DasKeyboard/Daskeyboard.io/blob/master/_includes/script-examples/cpu-percentage/node.md
