### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by macdja38** [daskeyboard/daskeyboard.io#5]
The local instructions here seem to use https, I didn't have any success using https, should the instructions say http instead?

Section:
https://github.com/DasKeyboard/q/blob/master/q-api-doc.md#creating-a-signal-cloud-and-local

**Comment by MargauxMasson** [comment]
Yes the local api is using an http request and not an https, the documentation will be updated, thank you for the feedback.

**Comment by macdja38** [comment]
Fixed in https://github.com/DasKeyboard/q/commit/1bd2abe77717faa8af8d75d47b1d035ff62ab7dd
