### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Will-iam-Chen** [daskeyboard/daskeyboard.io#53]
Running the installer for version 2.0.3 "fails" with this message:

CreateProcess failed; code 2.
The system cannot find the file specified.

The file in question is Service Module.exe. After the installer closes, the "q" splash screen shows up for a couple seconds then crashes with no message. At this point there is no Das Keyboard service running, and manually running the service from the install directory doesn't change DasKeyboardQInstaller.exe's behavior (splash screen then crash).

No logs are generated in \AppData\Roaming\das-keyboard-q\logs.

**Comment by Mubramaj** [comment]
We released a new version that fixes this issue https://www.daskeyboard.io/get-started/software/
