### ISSUE TITLE
UK layout 5Q backslash not illuminated

### ISSUE THREAD

**Issue by DavidJohnGee** [daskeyboard/daskeyboard.io#55]
Just received my 5Q keyboard and it feels quite nice. The only disappointment is the key the backslash & pipe key does not illuminate. The "Das Keyboard Q" application recognises this as an American keyboard and although when hitting the keys, the correct characters are sent, it's not the case when managing key illumination through the application.

The \ & | key (second row from bottom, second key from left) is permanently un-lit and there are no options to illuminate it, or certainly non that I can find on the application. 

UK layout with latest firmware 7.4.18.

I've tried setting the key colour through the shell script example and all that happened was the keys on the grid, 2,4 and 2,3 illuminated together, but my keyboard has independent 2,3 and 2,4 instead of the longer shift key. 

Was so looking forward to getting this keyboard and I'm a bit miffed. Any idea on a time fix?

Thanks,
D

**Comment by DavidJohnGee** [comment]
Nothing yet? Not even an acknowledgement?

**Comment by supercobra** [comment]
@DavidJohnGee this is the github repo for the documentation website. If you are having issue with the hardware and software please discuss it on the forum: https://qforum.daskeyboard.com/
