### ISSUE TITLE
daskeyboard Software on archlinux

### ISSUE THREAD

**Issue by joda2802** [daskeyboard/daskeyboard.io#60]
Hey I have a problem with running the Software on archlinux. Since It is only available as a .deb file, I had to manually convert/install it. Finally, I got it running but unfortunately it doesn't recognize my device. I also tested the keyboard on my Ubuntu laptop, where it worked fine to prevent hardware or firmware issues. Are there other Archlinux users out there to help me?

**Comment by supercobra** [comment]
@joda2802 I would recommend to post this message on the Q forum: https://qforum.daskeyboard.com

**Comment by joda2802** [comment]
@supercobra Thank you I wasn't aware of that forum.
