### ISSUE TITLE
Issue from website page Get Started: Firmware Upgrade

### ISSUE THREAD

**Issue by Curtis217** [daskeyboard/daskeyboard.io#61]
From URL: https://www.daskeyboard.io/get-started/firmware.md

Cannot get X50 to connect to DaskeyboardQ software.

**Comment by ghennion** [comment]
Hi @Curtis217, could you please open a ticket with Das Keyboard support so we can help you with this issue? https://daskeyboard.mojohelpdesk.com/mytickets/create#/ticket-form-selection

**Comment by fabiendv** [comment]
Our latest releases address these issues.
[Changelog](https://www.daskeyboard.io/updates/changelog/)
[Download](https://www.daskeyboard.io/get-started/software/)
