### ISSUE TITLE
Issue from website page Get signals

### ISSUE THREAD

**Issue by rideron89** [daskeyboard/daskeyboard.io#66]
From URL: https://www.daskeyboard.io/api-ressources/signal/get-signals.md

There is no documentation for using the localhost API. The page says `Q Cloud Only` but below that has a deprecation notice saying to use the `localhost API or Q Applet API`.

I have tried calling `/api/1.0/signals` and `/signals` and both resources return the following message:
```
Cannot GET /api/1.0/signals
```

**Comment by Mubramaj** [comment]
Hi @rideron89 ,

[https://www.daskeyboard.io/api-resources/signal/get-signals/](https://www.daskeyboard.io/api-resources/signal/get-signals/)

This route can be used only with the cloud API, which is now deprecated but still works.

To get the signals from the local API I advice you to use this endpoint instead: 
[https://www.daskeyboard.io/api-resources/signal/get-all-shadow-signals/](https://www.daskeyboard.io/api-resources/signal/get-all-shadow-signals/)

**Comment by fabiendv** [comment]
Do not hesitate to contact [our support](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form-selection) if any further help is needed.

Closing.
