### ISSUE TITLE
make software working for macos

### ISSUE THREAD

**Issue by badummtss** [daskeyboard/daskeyboard.io#67]
That's not really funny, I'm working with an Hackintosh and using my X50q with Windows 10 and macos mojave.
Why there isn't a support for using the RGB Software and the Dashlets within Macos??

Is it only for the 5q? I'm not ready to pay more for something that could work that way !!!

Please make the software also working for macos!!!!!

**Comment by fabiendv** [comment]
Thank you. 
I sent a request to the product team. 
I am going to close this issue now.

**Comment by louisspahn** [comment]
Why was this closed? Do you have any update on the ask?
