### ISSUE TITLE
Security contact information 

### ISSUE THREAD

**Issue by GriffinMB** [daskeyboard/daskeyboard.io#68]
Hello! Is there a contact address for reporting security issues? I saw that previous concerns were just opened as issues on GitHub, is that the intended venue for reporting?

I also posted this question on the forum, but figure there may be a better chance of reaching a security contact here!

Also, love the keyboards! I have two :)

**Comment by supercobra** [comment]
Please open a ticket here: https://daskeyboard.mojohelpdesk.com/

Thank you!
