### ISSUE TITLE
Doesn't recognize keyboard

### ISSUE THREAD

**Issue by urossavelj** [daskeyboard/daskeyboard.io#69]
das-keyboard-q says disconnected forever until I restart the pc. Than it works till the next time the computer goes to sleep/hibernate.

I have a 4Q with the latest firmware and q software.

**Comment by LastStupid** [comment]
+1

Hi, I got the same problem with my Das Keyboard 4Q.  Did you find a solution?  I am tire of restarting my PC...
Thanks

**Comment by fabiendv** [comment]
Can you submit a request through our support [here](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form/19780)?

Closing. But I keep [a similar thread](https://github.com/daskeyboard/daskeyboard.io/issues/82) open.
