### ISSUE TITLE
5Q locks up daily. Must be unplugged and replugged.

### ISSUE THREAD

**Issue by Dyltone** [daskeyboard/daskeyboard.io#70]
When the device locks up, no keys work and usually there are a few keys still backlit, but most are dark.

Running latest firmware which stated that it fixed intermittent reboots. I had those reboots prior to the firmware, but I still get the USB disconnect/reconnect sounds from time to time.

I attempted to use USBLogView to see what is causing the issue but it doesn't log the disconnects consistently.

Also, the built in logs (quio.log and quio1.log) are both over a month old.

**Comment by fabiendv** [comment]
Can you report this behavior through our support [here](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form/19780)? It will provide a better assistance.

Closing.
