### ISSUE TITLE
X50Q Mac and Linux support

### ISSUE THREAD

**Issue by ash0x0** [daskeyboard/daskeyboard.io#71]
Are there any plans for X50Q to be supported for mac and linux? I know this is probably not the appropriate forum but if you don't plan to support it then what will I be missing out on if I'm not using the firmware. And is the support going to be a driver issue? If I run Q app in WINE, what's expected there?

EDIT: So let me ask this appropriately. I understand that Das has no plans to support, so just disregard everything I said. My question is now this: would it be possible for me to create support for X50Q or do you guys use proprietary blobs for interface?

**Comment by deppiedave64** [comment]
I just bought a X50Q as a main Linux user. The keyboard itself is great, but it would be even better if there were some form of Linux support, either by Your team or by giving the community access to the necessary code to do it themselves. If we can't get the complete Q app, maybe a CLI API for controlling RGB?

**Comment by louisspahn** [comment]
+1 for Mac support!!

**Comment by fabiendv** [comment]
Be free to send your suggestions through [our dedicated form](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form/37017).
We gather all ideas from here, in order to set our next milestones.

Closing.
