### ISSUE TITLE
Q software is not working

### ISSUE THREAD

**Issue by physixtential** [daskeyboard/daskeyboard.io#72]
I just got my x50q and the q software is not effecting the keyboard at all. I have tried general rgb schemes as well as intalling applets and nothing changes the physical keyboard despite the dashboard representation changing as expected. What is going on?

**Comment by 7ranceaddic7** [comment]
I just received the X50Q today.  Completed the setup process and updated the firmware.

Unfortunately, after cycling through the built-in profiles the Q  software RGB profiles no longer activate when selected.

**Comment by Maltavius** [comment]
So I know this is a bit late... but go into services.msc and restart the "Das Keyboard Q-Service" and it should start responding.

**Comment by fabiendv** [comment]
I would say the service was not synchronized.

If restarting does not help, please [contact our support](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form-selection). 

Closing.
