### ISSUE TITLE
4Q disconnected

### ISSUE THREAD

**Issue by un4tuner** [daskeyboard/daskeyboard.io#74]
After reboot I am able to connect to keyboard, change its settings and add some applets, but during working day it just stops service and disconnects, so applets freeze on last state.
![image](https://user-images.githubusercontent.com/43656714/67938744-26e0f080-fbe1-11e9-8049-6b6ff66c629c.png)

**Comment by urossavelj** [comment]
I guess that you have the same issue as I opened #69 ?

I noticed that if you open task manager and start the service manually again, called "das_keyboard_q_service" than it starts to work again. But after some time it will crash again.

**Comment by un4tuner** [comment]
> I guess that you have the same issue as I opened #69 ?
> 
> I noticed that if you open task manager and start the service manually again, called "das_keyboard_q_service" than it starts to work again. But after some time it will crash again.

Oops i didn't see your issue. =(
Problem is - I can't restart service, as I'm not admin in my office - I had to ask our sysadmin to install Q software and register service. I can't ask our IT crew to relaunch service every time it gets stuck (also it's not normal if you ask me).

**Comment by urossavelj** [comment]
It surely is not normal, but the das keyboard team doesn't seem to care much. They have issues opened from 2018, still unsolved.

**Comment by fabiendv** [comment]
We care, and we would love to hear more to fix this issue.

Can you submit a request through our support [here](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form/19780)?

Closing. But I keep [a similar thread](https://github.com/daskeyboard/daskeyboard.io/issues/82) open.
