### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by yaonggcx** [daskeyboard/daskeyboard.io#76]
From URL: https://www.daskeyboard.io/get-started/software.md

I am getting the following errors after downloading the installation .pkg. Please see the screenshot below:
![Screenshot 2019-12-06 at 3 53 43 PM](https://user-images.githubusercontent.com/54901319/70306126-fe33c280-1840-11ea-9ed8-a5d28acb6c62.png)

**Comment by Mubramaj** [comment]
can you please open a ticket at https://daskeyboard.mojohelpdesk.com
