### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by xxedgexx** [daskeyboard/daskeyboard.io#77]
From URL: https://www.daskeyboard.io/get-started/software.md

Q software on Mac OS Catalina just becomes unresponsive at the beginning of the install.  I can't proceed.  Kill it and tried multiple times.  Just becomes unresponsive immediately.

**Comment by Mubramaj** [comment]
can you please open a ticket at [https://daskeyboard.mojohelpdesk.com](https://daskeyboard.mojohelpdesk.com)
