### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by Maldenite** [daskeyboard/daskeyboard.io#78]
From URL: https://www.daskeyboard.io/get-started/software.md it will not allow update because Apple cannot verify for malware.
![Screenshot 2020-02-17 11 18 34](https://user-images.githubusercontent.com/747724/74675359-00879680-5179-11ea-841b-414b67ee427d.png)

**Comment by fabiendv** [comment]
Related to [this issue](https://github.com/daskeyboard/daskeyboard.io/issues/76).

[Our support](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form-selection) will provide a more efficient assistance.

Closing.
