### ISSUE TITLE
No user friendly way to revoke clients

### ISSUE THREAD

**Issue by jordanbtucker** [daskeyboard/daskeyboard.io#8]
I have not found a user friendly way to revoke access from a client application, like IFTTT or Zapier. The only way I have found is [through the API](https://github.com/DasKeyboard/q/blob/master/q-api-doc.md).

Are there plans to implement a web page to allow users to revoke client access?

**Comment by supercobra** [comment]
You may want to try: https://q.daskeyboard.com/thirdparty/manage
