### ISSUE TITLE
Issue from website page Getting Started with Q

### ISSUE THREAD

**Issue by sawickham** [daskeyboard/daskeyboard.io#81]
From URL: https://www.daskeyboard.io/get-started/software/

Download can't be installed on the latest macOS, Catalina. I've been trying to get this new Kickstarter keyboard to work, off and on, since I finally received it...

<img width="408" alt="Screen Shot 2020-03-13 at 11 07 53 AM" src="https://user-images.githubusercontent.com/1081025/76638823-16d80680-651b-11ea-9270-5cbb252dac54.png">

**Comment by fabiendv** [comment]
Related to [this issue](https://github.com/daskeyboard/daskeyboard.io/issues/76).

[Our support](https://daskeyboard.mojohelpdesk.com/login/create_request#/ticket-form-selection) will provide a more efficient assistance.

Closing.
