### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by liamneville** [daskeyboard/daskeyboard.io#88]
I have a Das 4Q and it continues to have an issue where switching between windows and macOS causes it not be recognized when plugged back into windows machine. I am able to type, but the keyboard is not recognized by the Q Software app on windows and I can't change settings. This also occurs sometimes after just unplugging it and plugging it back in (without having used it on macOS). When I plug back into macOS it is recognized and works fine. The only way I've been able to get around this is just reinstalling the software on Windows which seems to reset things and keyboard is recognized. It is a bit annoying to have to reinstall the software nearly every day to get the full functionality from this. Any ideas on how to resolve the issue I am experiencing when switching back to windows?

**Comment by Mubramaj** [comment]
Hi @liamneville can you please open a ticket at [daskeyboard.mojohelpdesk.com](https://daskeyboard.mojohelpdesk.com) and the tech support will help you.
