### ISSUE TITLE
X50Q Keyboard loses color profile and turns red.

### ISSUE THREAD

**Issue by Maltavius** [daskeyboard/daskeyboard.io#93]
Since this software is so buggy and a memory hog for doing nothing I usually shut it off.

It's set on autostart on reboot though.

So sometimes my custom color profile just stops working and the keyboard turns a solid color, usually red.
Starting the Das Keyboard-q software and changing color profiles doesn't work at all.

**Comment by Maltavius** [comment]
The issue seems to be that Quitting the Software doesn't Shut down the Das Keyboard Q-Service.
And that seems to be the one that is failing.

I upgraded from 3.2.6 to 3.2.8 and that restarted the service and after that the LEDs started responding again when changing color profiles.

**Comment by Mubramaj** [comment]
Hi @Maltavius ,

If you are still having issues can you open a ticket on our helpdesk https://daskeyboard.mojohelpdesk.com/ 

Thanks !
