### ISSUE TITLE
[need] Old Firmware for X50Q

### ISSUE THREAD

**Issue by jester187** [daskeyboard/daskeyboard.io#94]
Hey, since I upgraded my X50Q to the newest firmware, my LED for the volume control doesn't work anymore by using custom profiles, also what I don't like is by that firmware (0040) that they replaced "mute/unmute" by pushing the volume button to "open Q Software"

If someone has a link to the old firmwares would be awesome. Thanks

**Comment by Mubramaj** [comment]
Hi @jester187, can you open a ticket on our helpdesk, the tech support will be able to help you 
https://daskeyboard.mojohelpdesk.com/
