### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by tb46uk** [daskeyboard/daskeyboard.io#99]
From URL: https://www.daskeyboard.io/get-started/software.md

**Comment by tb46uk** [comment]
run the installation succesfully. on my MacBook 11.3.2 but the Q app still opens with 3.2.8 firmware

**Comment by Perlets9** [comment]
same here, macOS v11.2.3

**Comment by Mubramaj** [comment]
Hi everyone,

Thank you for reporting this issue. It has been fixed in version 3.3.1 that we just released.

https://www.daskeyboard.io/get-started/software/
